# Employee Performance Analysis

#### Code: 10281
### INX Future Inc.

# DATA PROCESSING PIPELINE

## Importing Libraries

In [86]:
import pandas as pd
import numpy as np
pd.set_option('display.max_columns', None)

## Loading Dataset

In [87]:
df = pd.read_excel("C:\\Users\\navee\\Downloads\\INX_Future_Inc_Employee_Performance_CDS_Project\\Data\\Raw\\INX_Future_Inc_Employee_Performance_CDS_Project2_Data_V1.8.xls",engine="xlrd")

df

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,OverTime,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,4,55,3,2,4,1,No,12,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,4,42,3,2,1,2,No,12,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,4,48,2,3,1,5,Yes,21,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,2,73,2,5,4,3,No,15,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,1,84,3,2,1,8,No,14,4,10,1,3,2,2,2,2,No,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,E100992,27,Female,Medical,Divorced,Sales,Sales Executive,Travel_Frequently,3,1,4,71,4,2,4,1,Yes,20,2,6,3,3,6,5,0,4,No,4
1196,E100993,37,Male,Life Sciences,Single,Development,Senior Developer,Travel_Rarely,10,2,4,80,4,1,4,3,No,17,1,4,2,3,1,0,0,0,No,3
1197,E100994,50,Male,Medical,Married,Development,Senior Developer,Travel_Rarely,28,1,4,74,4,1,3,1,Yes,11,3,20,3,3,20,8,3,8,No,3
1198,E100995,34,Female,Medical,Single,Data Science,Data Scientist,Travel_Rarely,9,3,4,46,2,3,2,1,No,14,2,9,3,4,8,7,7,7,No,3
1199,E100998,24,Female,Life Sciences,Single,Sales,Sales Executive,Travel_Rarely,3,2,1,65,3,2,3,9,No,14,1,4,3,3,2,2,2,0,Yes,2

In [88]:
# Preview data
df.head()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,OverTime,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,E1001000,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,4,55,3,2,4,1,No,12,4,10,2,2,10,7,0,8,No,3
1,E1001006,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,4,42,3,2,1,2,No,12,4,20,2,3,7,7,1,7,No,3
2,E1001007,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,4,48,2,3,1,5,Yes,21,3,20,2,3,18,13,1,12,No,4
3,E1001009,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,2,73,2,5,4,3,No,15,2,23,2,2,21,6,12,6,No,3
4,E1001010,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,1,84,3,2,1,8,No,14,4,10,1,3,2,2,2,2,No,3

In [89]:
df.tail()

,EmpNumber,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,OverTime,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
1195,E100992,27,Female,Medical,Divorced,Sales,Sales Executive,Travel_Frequently,3,1,4,71,4,2,4,1,Yes,20,2,6,3,3,6,5,0,4,No,4
1196,E100993,37,Male,Life Sciences,Single,Development,Senior Developer,Travel_Rarely,10,2,4,80,4,1,4,3,No,17,1,4,2,3,1,0,0,0,No,3
1197,E100994,50,Male,Medical,Married,Development,Senior Developer,Travel_Rarely,28,1,4,74,4,1,3,1,Yes,11,3,20,3,3,20,8,3,8,No,3
1198,E100995,34,Female,Medical,Single,Data Science,Data Scientist,Travel_Rarely,9,3,4,46,2,3,2,1,No,14,2,9,3,4,8,7,7,7,No,3
1199,E100998,24,Female,Life Sciences,Single,Sales,Sales Executive,Travel_Rarely,3,2,1,65,3,2,3,9,No,14,1,4,3,3,2,2,2,0,Yes,2

## Basic Info & Understanding

In [90]:
# Shape of dataset
print("Shape:", df.shape)

Shape: (1200, 28)

In [91]:
# Column names
print("Columns:\n", df.columns)

Columns:
 Index(['EmpNumber', 'Age', 'Gender', 'EducationBackground', 'MaritalStatus',
       'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency',
       'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction',
       'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel',
       'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime',
       'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction',
       'TotalWorkExperienceInYears', 'TrainingTimesLastYear',
       'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany',
       'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'PerformanceRating'],
      dtype='object')

In [92]:
# Data types
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1200 entries, 0 to 1199
Data columns (total 28 columns):
 #   Column                        Non-Null Count  Dtype
---  ------                        --------------  -----
 0   EmpNumber                     1200 non-null   object
 1   Age                           1200 non-null   int64
 2   Gender                        1200 non-null   object
 3   EducationBackground           1200 non-null   object
 4   MaritalStatus                 1200 non-null   object
 5   EmpDepartment                 1200 non-null   object
 6   EmpJobRole                    1200 non-null   object
 7   BusinessTravelFrequency       1200 non-null   object
 8   DistanceFromHome              1200 non-null   int64
 9   EmpEducationLevel             1200 non-null   int64
 10  EmpEnvironmentSatisfaction    1200 non-null   int64
 11  EmpHourlyRate                 1200 non-null   int64
 12  EmpJobInvolvement             1200 non-null   int64
 13  EmpJobLevel                   1200 non-null   int64
 14  EmpJobSatisfaction            1200 non-null   int64
 15  NumCompaniesWorked            1200 non-null   int64
 16  OverTime                      1200 non-null   object
 17  EmpLastSalaryHikePercent      1200 non-null   int64
 18  EmpRelationshipSatisfaction   1200 non-null   int64
 19  TotalWorkExperienceInYears    1200 non-null   int64
 20  TrainingTimesLastYear         1200 non-null   int64
 21  EmpWorkLifeBalance            1200 non-null   int64
 22  ExperienceYearsAtThisCompany  1200 non-null   int64
 23  ExperienceYearsInCurrentRole  1200 non-null   int64
 24  YearsSinceLastPromotion       1200 non-null   int64
 25  YearsWithCurrManager          1200 non-null   int64
 26  Attrition                     1200 non-null   object
 27  PerformanceRating             1200 non-null   int64
dtypes: int64(19), object(9)
memory usage: 262.6+ KB

In [93]:
# Statistical summary
df.describe()

,Age,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,PerformanceRating
count,1200.000000,1200.000000,1200.00000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000,1200.000000
mean,36.918333,9.165833,2.89250,2.715833,65.981667,2.731667,2.067500,2.732500,2.665000,15.222500,2.725000,11.330000,2.785833,2.744167,7.077500,4.291667,2.194167,4.105000,2.948333
std,9.087289,8.176636,1.04412,1.090599,20.211302,0.707164,1.107836,1.100888,2.469384,3.625918,1.075642,7.797228,1.263446,0.699374,6.236899,3.613744,3.221560,3.541576,0.518866
min,18.000000,1.000000,1.00000,1.000000,30.000000,1.000000,1.000000,1.000000,0.000000,11.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,2.000000
25%,30.000000,2.000000,2.00000,2.000000,48.000000,2.000000,1.000000,2.000000,1.000000,12.000000,2.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000,3.000000
50%,36.000000,7.000000,3.00000,3.000000,66.000000,3.000000,2.000000,3.000000,2.000000,14.000000,3.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000,3.000000
75%,43.000000,14.000000,4.00000,4.000000,83.000000,3.000000,3.000000,4.000000,4.000000,18.000000,4.000000,15.000000,3.000000,3.000000,10.000000,7.000000,3.000000,7.000000,3.000000
max,60.000000,29.000000,5.00000,4.000000,100.000000,4.000000,5.000000,4.000000,9.000000,25.000000,4.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000,4.000000

## Checking Missing Values

In [94]:
df.isnull().sum()

EmpNumber                       0
Age                             0
Gender                          0
EducationBackground             0
MaritalStatus                   0
EmpDepartment                   0
EmpJobRole                      0
BusinessTravelFrequency         0
DistanceFromHome                0
EmpEducationLevel               0
EmpEnvironmentSatisfaction      0
EmpHourlyRate                   0
EmpJobInvolvement               0
EmpJobLevel                     0
EmpJobSatisfaction              0
NumCompaniesWorked              0
OverTime                        0
EmpLastSalaryHikePercent        0
EmpRelationshipSatisfaction     0
TotalWorkExperienceInYears      0
TrainingTimesLastYear           0
EmpWorkLifeBalance              0
ExperienceYearsAtThisCompany    0
ExperienceYearsInCurrentRole    0
YearsSinceLastPromotion         0
YearsWithCurrManager            0
Attrition                       0
PerformanceRating               0
dtype: int64

No missing values

## Checking Duplicate Rows

In [95]:
df.duplicated().sum()

np.int64(0)

No duplicate values

## Standardizing Column Names

In [96]:
df.columns = df.columns.str.strip().str.replace(' ', '_')
df.columns

Index(['EmpNumber', 'Age', 'Gender', 'EducationBackground', 'MaritalStatus',
       'EmpDepartment', 'EmpJobRole', 'BusinessTravelFrequency',
       'DistanceFromHome', 'EmpEducationLevel', 'EmpEnvironmentSatisfaction',
       'EmpHourlyRate', 'EmpJobInvolvement', 'EmpJobLevel',
       'EmpJobSatisfaction', 'NumCompaniesWorked', 'OverTime',
       'EmpLastSalaryHikePercent', 'EmpRelationshipSatisfaction',
       'TotalWorkExperienceInYears', 'TrainingTimesLastYear',
       'EmpWorkLifeBalance', 'ExperienceYearsAtThisCompany',
       'ExperienceYearsInCurrentRole', 'YearsSinceLastPromotion',
       'YearsWithCurrManager', 'Attrition', 'PerformanceRating'],
      dtype='object')

Removes unwanted spaces<br>
Replaces spaces with underscores<br>
Makes column names easier to use in code<br>

## Checking Unique Values in Categorical Columns

In [97]:
cat_cols = df.select_dtypes(include='object').columns

for col in cat_cols:
    print(f"{col}: {df[col].unique()}")

EmpNumber: ['E1001000' 'E1001006' 'E1001007' ... 'E100994' 'E100995' 'E100998']
Gender: ['Male' 'Female']
EducationBackground: ['Marketing' 'Life Sciences' 'Human Resources' 'Medical' 'Other'
 'Technical Degree']
MaritalStatus: ['Single' 'Married' 'Divorced']
EmpDepartment: ['Sales' 'Human Resources' 'Development' 'Data Science'
 'Research & Development' 'Finance']
EmpJobRole: ['Sales Executive' 'Manager' 'Developer' 'Sales Representative'
 'Human Resources' 'Senior Developer' 'Data Scientist'
 'Senior Manager R&D' 'Laboratory Technician' 'Manufacturing Director'
 'Research Scientist' 'Healthcare Representative' 'Research Director'
 'Manager R&D' 'Finance Manager' 'Technical Architect' 'Business Analyst'
 'Technical Lead' 'Delivery Manager']
BusinessTravelFrequency: ['Travel_Rarely' 'Travel_Frequently' 'Non-Travel']
OverTime: ['No' 'Yes']
Attrition: ['No' 'Yes']

Displays unique categories in each categorical column<br>
**Helps identify:**<br>
Inconsistent labels<br>
Typographical errors<br>

## Removing Irrelevant Columns

In [98]:
df.drop(['EmpNumber'], axis=1, inplace=True)

EmployeeNumber → unique ID (not useful for analysis)<br>
Removing them improves model performance

## Separating Target First

In [99]:
X = df.drop('PerformanceRating', axis=1)
y = df['PerformanceRating']

## Detecting Outliers (IQR Method)

In [100]:
num_cols = X.select_dtypes(include=np.number).columns

for col in num_cols:
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    print(f"{col}: Lower={lower}, Upper={upper}")

Age: Lower=10.5, Upper=62.5
DistanceFromHome: Lower=-16.0, Upper=32.0
EmpEducationLevel: Lower=-1.0, Upper=7.0
EmpEnvironmentSatisfaction: Lower=-1.0, Upper=7.0
EmpHourlyRate: Lower=-4.5, Upper=135.5
EmpJobInvolvement: Lower=0.5, Upper=4.5
EmpJobLevel: Lower=-2.0, Upper=6.0
EmpJobSatisfaction: Lower=-1.0, Upper=7.0
NumCompaniesWorked: Lower=-3.5, Upper=8.5
EmpLastSalaryHikePercent: Lower=3.0, Upper=27.0
EmpRelationshipSatisfaction: Lower=-1.0, Upper=7.0
TotalWorkExperienceInYears: Lower=-7.5, Upper=28.5
TrainingTimesLastYear: Lower=0.5, Upper=4.5
EmpWorkLifeBalance: Lower=0.5, Upper=4.5
ExperienceYearsAtThisCompany: Lower=-7.5, Upper=20.5
ExperienceYearsInCurrentRole: Lower=-5.5, Upper=14.5
YearsSinceLastPromotion: Lower=-4.5, Upper=7.5
YearsWithCurrManager: Lower=-5.5, Upper=14.5

Using Interquartile Range (IQR) method<br>
Helps detect extreme values (outliers)<br>
Outliers can negatively affect model performance

## Handling Outliers (Capping)

In [101]:
for col in num_cols:
    Q1 = X[col].quantile(0.25)
    Q3 = X[col].quantile(0.75)
    IQR = Q3 - Q1
    
    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR
    
    X[col] = np.where(X[col] > upper, upper,
              np.where(X[col] < lower, lower, X[col]))

Capping extreme values instead of removing them<br>
Prevents data loss while controlling outliers

In [102]:
df_cleaned = pd.concat([X, y], axis=1)

## Final Data Check

In [103]:
df_cleaned

,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,OverTime,EmpLastSalaryHikePercent,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,32.0,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10.0,3.0,4.0,55.0,3.0,2.0,4.0,1.0,No,12.0,4.0,10.0,2.0,2.0,10.0,7.0,0.0,8.0,No,3
1,47.0,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14.0,4.0,4.0,42.0,3.0,2.0,1.0,2.0,No,12.0,4.0,20.0,2.0,3.0,7.0,7.0,1.0,7.0,No,3
2,40.0,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5.0,4.0,4.0,48.0,2.0,3.0,1.0,5.0,Yes,21.0,3.0,20.0,2.0,3.0,18.0,13.0,1.0,12.0,No,4
3,41.0,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10.0,4.0,2.0,73.0,2.0,5.0,4.0,3.0,No,15.0,2.0,23.0,2.0,2.0,20.5,6.0,7.5,6.0,No,3
4,60.0,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16.0,4.0,1.0,84.0,3.0,2.0,1.0,8.0,No,14.0,4.0,10.0,1.0,3.0,2.0,2.0,2.0,2.0,No,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,27.0,Female,Medical,Divorced,Sales,Sales Executive,Travel_Frequently,3.0,1.0,4.0,71.0,4.0,2.0,4.0,1.0,Yes,20.0,2.0,6.0,3.0,3.0,6.0,5.0,0.0,4.0,No,4
1196,37.0,Male,Life Sciences,Single,Development,Senior Developer,Travel_Rarely,10.0,2.0,4.0,80.0,4.0,1.0,4.0,3.0,No,17.0,1.0,4.0,2.0,3.0,1.0,0.0,0.0,0.0,No,3
1197,50.0,Male,Medical,Married,Development,Senior Developer,Travel_Rarely,28.0,1.0,4.0,74.0,4.0,1.0,3.0,1.0,Yes,11.0,3.0,20.0,3.0,3.0,20.0,8.0,3.0,8.0,No,3
1198,34.0,Female,Medical,Single,Data Science,Data Scientist,Travel_Rarely,9.0,3.0,4.0,46.0,2.0,3.0,2.0,1.0,No,14.0,2.0,9.0,3.0,4.0,8.0,7.0,7.0,7.0,No,3
1199,24.0,Female,Life Sciences,Single,Sales,Sales Executive,Travel_Rarely,3.0,2.0,1.0,65.0,3.0,2.0,3.0,8.5,No,14.0,1.0,4.0,3.0,3.0,2.0,2.0,2.0,0.0,Yes,2

Verifying cleaned dataset<br>
Ensuring all transformations are applied correctly

In [104]:
df_cleaned.dtypes

Age                             float64
Gender                           object
EducationBackground              object
MaritalStatus                    object
EmpDepartment                    object
EmpJobRole                       object
BusinessTravelFrequency          object
DistanceFromHome                float64
EmpEducationLevel               float64
EmpEnvironmentSatisfaction      float64
EmpHourlyRate                   float64
EmpJobInvolvement               float64
EmpJobLevel                     float64
EmpJobSatisfaction              float64
NumCompaniesWorked              float64
OverTime                         object
EmpLastSalaryHikePercent        float64
EmpRelationshipSatisfaction     float64
TotalWorkExperienceInYears      float64
TrainingTimesLastYear           float64
EmpWorkLifeBalance              float64
ExperienceYearsAtThisCompany    float64
ExperienceYearsInCurrentRole    float64
YearsSinceLastPromotion         float64
YearsWithCurrManager            float64
Attrition                        object
PerformanceRating                 int64
dtype: object

Confirming datatypes

In [105]:
df_cleaned.shape

(1200, 27)

Confirming final dataset size after cleaning

## Making Float values to stay intact in Excel Format

In [106]:
# Defining the columns
float_cols = [
    'Age',
    'DistanceFromHome',
    'EmpHourlyRate',
    'TotalWorkExperienceInYears',
    'ExperienceYearsAtThisCompany',
    'ExperienceYearsInCurrentRole',
    'YearsSinceLastPromotion',
    'YearsWithCurrManager'
]

# Converting them to float
df_cleaned[float_cols] = df_cleaned[float_cols].astype('float64')

## Typecasting some of the float values back into int

In [107]:
int_cols = df_cleaned.columns.intersection([
'EmpEducationLevel',
'EmpEnvironmentSatisfaction',
'EmpJobInvolvement',
'EmpJobLevel',
'EmpJobSatisfaction',
'NumCompaniesWorked',
'EmpLastSalaryHikePercent',
'EmpRelationshipSatisfaction',
'TrainingTimesLastYear',
'EmpWorkLifeBalance',
'PerformanceRating'
])

df_cleaned[int_cols] = df_cleaned[int_cols].astype('int64')

In [108]:
df_cleaned.dtypes

Age                             float64
Gender                           object
EducationBackground              object
MaritalStatus                    object
EmpDepartment                    object
EmpJobRole                       object
BusinessTravelFrequency          object
DistanceFromHome                float64
EmpEducationLevel                 int64
EmpEnvironmentSatisfaction        int64
EmpHourlyRate                   float64
EmpJobInvolvement                 int64
EmpJobLevel                       int64
EmpJobSatisfaction                int64
NumCompaniesWorked                int64
OverTime                         object
EmpLastSalaryHikePercent          int64
EmpRelationshipSatisfaction       int64
TotalWorkExperienceInYears      float64
TrainingTimesLastYear             int64
EmpWorkLifeBalance                int64
ExperienceYearsAtThisCompany    float64
ExperienceYearsInCurrentRole    float64
YearsSinceLastPromotion         float64
YearsWithCurrManager            float64
Attrition                        object
PerformanceRating                 int64
dtype: object

Keeping as INT (discrete / ordinal values) <br>
Keeping as FLOAT (continuous / measurable values)

"The dataset was found to be clean with no missing values. \
Duplicate records were not found, irrelevant features were dropped, and \
outliers were treated using the IQR capping method to ensure robust model performance."

# Saving Processed Dataframe to Excel

In [112]:
df_cleaned.to_excel("employee_performance_processed.xlsx", index=False)