# Employee Performance Analysis

#### Code: 10281
### INX Future Inc.

# Feature engineering

## Importing Libraries

In [2]:
import pandas as pd
import numpy as np

Required for data manipulation and creating new features

## Load Cleaned Dataset

In [3]:
df = pd.read_excel("C:\\Users\\navee\\Downloads\\INX_Future_Inc_Employee_Performance_CDS_Project\\Data\\Processed\\employee_performance_processed.xlsx")

df.head()

,Age,Gender,EducationBackground,MaritalStatus,EmpDepartment,EmpJobRole,BusinessTravelFrequency,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,...,EmpRelationshipSatisfaction,TotalWorkExperienceInYears,TrainingTimesLastYear,EmpWorkLifeBalance,ExperienceYearsAtThisCompany,ExperienceYearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager,Attrition,PerformanceRating
0,32,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,10,3,4,...,4,10.0,2,2,10.0,7.0,0.0,8.0,No,3
1,47,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,14,4,4,...,4,20.0,2,3,7.0,7.0,1.0,7.0,No,3
2,40,Male,Life Sciences,Married,Sales,Sales Executive,Travel_Frequently,5,4,4,...,3,20.0,2,3,18.0,13.0,1.0,12.0,No,4
3,41,Male,Human Resources,Divorced,Human Resources,Manager,Travel_Rarely,10,4,2,...,2,23.0,2,2,20.5,6.0,7.5,6.0,No,3
4,60,Male,Marketing,Single,Sales,Sales Executive,Travel_Rarely,16,4,1,...,4,10.0,1,3,2.0,2.0,2.0,2.0,No,3

Load the already cleaned dataset<br>
Feature engineering done after cleaning

# Handling Categorical Variables

## Identifying Categorical Columns

In [4]:
cat_cols = df.select_dtypes(include='object').columns
print(cat_cols)

Index(['Gender', 'EducationBackground', 'MaritalStatus', 'EmpDepartment',
       'EmpJobRole', 'BusinessTravelFrequency', 'OverTime', 'Attrition'],
      dtype='object')

## Label Encoding (Binary Columns)

In [5]:
from sklearn.preprocessing import LabelEncoder

le = LabelEncoder()

binary_cols = ['Attrition', 'Gender', 'OverTime']

for col in binary_cols:
    df[col] = le.fit_transform(df[col])

Converts Yes/No or Male/Female → 0/1<br>
Required for machine learning models

## One-Hot Encoding (Multi-category Columns)

In [6]:
df = pd.get_dummies(df, columns=[
    'BusinessTravelFrequency',
    'EmpDepartment',
    'EducationBackground',
    'EmpJobRole',
    'MaritalStatus'
], drop_first=True)

Converts categorical variables into numeric columns<br>
drop_first=True avoids multicollinearity

# Feature Creation

## Experience Ratio

In [7]:
df['ExperienceRatio'] = df['ExperienceYearsAtThisCompany'] / (df['TotalWorkExperienceInYears'] + 1)

Shows how long employee stayed in current company vs total experience<br>
Helps identify loyalty and stability

## Total Satisfaction Score

In [8]:
df['TotalSatisfaction'] = (
    df['EmpJobSatisfaction'] +
    df['EmpEnvironmentSatisfaction'] +
    df['EmpRelationshipSatisfaction'] +
    df['EmpWorkLifeBalance']
)

Combines all satisfaction metrics into one<br>
Strong predictor of performance

## Average Tenure per Role

In [9]:
df['AvgYearsPerRole'] = df['ExperienceYearsAtThisCompany'] / (df['ExperienceYearsInCurrentRole'] + 1)

Measures role stability<br>
Helps identify job switching frequency

## Scaling Features

## Separating Features & Target

In [10]:
X = df.drop('PerformanceRating', axis=1)
y = df['PerformanceRating']

## Applying Standard Scaling

In [11]:
from sklearn.preprocessing import StandardScaler

scaler = StandardScaler()

X_scaled = scaler.fit_transform(X)

Standardizes features (mean=0, std=1)<br>
Important for models like Logistic Regression

# Final Dataset

In [12]:
X = pd.DataFrame(X_scaled, columns=X.columns)

df_final = pd.concat([X, y.reset_index(drop=True)], axis=1)

df_final

,Age,Gender,DistanceFromHome,EmpEducationLevel,EmpEnvironmentSatisfaction,EmpHourlyRate,EmpJobInvolvement,EmpJobLevel,EmpJobSatisfaction,NumCompaniesWorked,...,EmpJobRole_Senior Developer,EmpJobRole_Senior Manager R&D,EmpJobRole_Technical Architect,EmpJobRole_Technical Lead,MaritalStatus_Married,MaritalStatus_Single,ExperienceRatio,TotalSatisfaction,AvgYearsPerRole,PerformanceRating
0,-0.541458,0.809427,0.102061,0.103000,1.177978,-0.543569,0.379608,-0.060955,1.151824,-0.683034,...,-0.212829,-0.112509,-0.0766,-0.180838,-0.916783,1.457738,1.186706,1.556760,-0.084878,3
1,1.109888,0.809427,0.591464,1.061145,1.177978,-1.187042,0.379608,-0.060955,-1.574386,-0.264636,...,-0.212829,-0.112509,-0.0766,-0.180838,-0.916783,1.457738,-0.876605,0.546697,-0.424759,3
2,0.339260,0.809427,-0.509693,1.061145,1.177978,-0.890055,-1.035081,0.842082,-1.574386,0.990556,...,-0.212829,-0.112509,-0.0766,-0.180838,1.090771,-0.685994,1.000543,0.041665,-0.052508,4
3,0.449349,0.809427,0.102061,1.061145,-0.656641,0.347393,-1.035081,2.648157,1.151824,0.153761,...,-0.212829,-0.112509,-0.0766,-0.180838,-0.916783,-0.685994,0.989877,-0.463366,1.436496,3
4,2.541054,0.809427,0.836165,1.061145,-1.573950,0.891870,0.379608,-0.060955,-1.574386,2.245748,...,-0.212829,-0.112509,-0.0766,-0.180838,-0.916783,1.457738,-1.419582,-0.968398,-0.613582,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1195,-1.091906,-1.235442,-0.754394,-1.813288,1.177978,0.248397,1.794297,-0.060955,1.151824,-0.683034,...,-0.212829,-0.112509,-0.0766,-0.180838,-0.916783,-0.685994,1.000543,1.051728,-0.311465,4
1196,0.008991,0.809427,0.102061,-0.855144,1.177978,0.693878,1.794297,-0.963992,1.151824,0.153761,...,4.698609,-0.112509,-0.0766,-0.180838,-0.916783,1.457738,-1.354424,0.546697,-0.311465,3
1197,1.440157,0.809427,2.304373,-1.813288,1.177978,0.396891,1.794297,-0.963992,0.243087,-0.683034,...,4.698609,-0.112509,-0.0766,-0.180838,1.090771,-0.685994,1.341842,1.051728,0.796296,3
1198,-0.321278,-1.235442,-0.020290,0.103000,1.177978,-0.989050,-1.035081,0.842082,-0.665650,-0.683034,...,-0.212829,-0.112509,-0.0766,-0.180838,-0.916783,1.457738,0.795763,0.546697,-0.311465,3
1199,-1.422176,-1.235442,-0.754394,-0.855144,-1.573950,-0.048590,0.379608,-0.060955,0.243087,2.245748,...,-0.212829,-0.112509,-0.0766,-0.180838,-0.916783,1.457738,-0.637695,-1.473430,-0.613582,2

In [13]:
df_final.to_excel("final_employee_performance_for_model.xlsx", index=False)